module.exports = {
  input: require('./webcomponents/input/input.webcomponent.js'),
  email: require('./webcomponents/email/email.webcomponent.js'),
  password: require('./webcomponents/password/password.webcomponent.js'),
  number: require('./webcomponents/number/number.webcomponent.js'),
  date: require('./webcomponents/date/date.webcomponent.js'),
  select: require('./webcomponents/select/select.webcomponent.js'),
  actionSheet: require('./webcomponents/action-sheet/action-sheet.webcomponent.js'),
  form: require('./webcomponents/form/form.webcomponent.js'),
  sidenav: require('./webcomponents/sidenav/sidenav.webcomponent.js'),
  checkbox: require('./webcomponents/checkbox/checkbox.webcomponent.js'),
  radio: require('./webcomponents/radio/radio.webcomponent.js'),
  dialog: require('./webcomponents/dialog/dialog.webcomponent.js'),
  button: require('./webcomponents/button/button.webcomponent.js'),
  search: require('./webcomponents/search/search.webcomponent.js'),
}
