module.exports = {
  input: require('./components/input/input.class.js'),
  email: require('./components/email/email.class.js'),
  password: require('./components/password/password.class.js'),
  hidden: require('./components/hidden/hidden.class.js'),
  number: require('./components/number/number.class.js'),
  date: require('./components/date/date.class.js'),
  backdrop: require('./components/backdrop/backdrop.class.js'),
  select: require('./components/select/select.class.js'),
  actionSheet: require('./components/action-sheet/action-sheet.class.js'),
  form: require('./components/form/form.class.js'),
  sidenav: require('./components/sidenav/sidenav.class.js'),
  checkbox: require('./components/checkbox/checkbox.class.js'),
  radio: require('./components/radio/radio.class.js'),
  dialog: require('./components/dialog/dialog.class.js'),
  button: require('./components/button/button.class.js'),
  search: require('./components/search/search.class.js'),
  list: require('./components/list/list.class.js'),
  code: require('./components/code/code.class.js'),
  image: require('./components/image/image.class.js'),
}
