#!/bin/bash

set -e

./node_modules/.bin/webpack docs/sources/app.js docs/vendor.js \
--devtool source-map \
--hide-modules true \
# --optimize-minimize \
--watch \

# https://www.npmjs.com/package/uglify-es
# ./node_modules/.bin/uglifyjs docs/vendor.js -c -m -o docs/vendor.min.js
