#!/bin/bash

set -e

[[ $1 = 'dev' ]] && watch='--watch' || watch=''

./node_modules/.bin/node-sass webcomponents/**/*.scss docs/vendor.css -q \
--output-style compressed \
--source-map true \
$watch
